### ISSUE TITLE
overriding logout button from admin-security-bundle

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-translatable-bundle#11]
when bundle is used together with admin-security-bundle button for logout and changing password is not visible. Template can be overriden in application, but maybe there can be faster solution included in this bundle.

Maybe it would require new block eg `navigation_right` for right side navigation in admin-bundle. There here button can be added?

**Comment by chives** [comment]
Closed by https://github.com/fsi-open/admin-bundle/pull/168
