### ISSUE TITLE
Fix compiler pass with latest admin-bundle (context builders)

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-translatable-bundle#52]
Adapt [CompilerPass](https://github.com/fsi-open/admin-translatable-bundle/blob/cefbad2cc65fb751a9b664d52bf8b696887ee1d5/DependencyInjection/Compiler/ResourceRepositoryPass.php#L30) to admin-bundle which [removes context builders](https://github.com/fsi-open/admin-bundle/pull/201)

**Comment by chives** [comment]
Resolved by #49
